// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/hub/v1/fleet.proto

package hubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceState int32

const (
	InstanceState_INSTANCE_STATE_UNKNOWN   InstanceState = 0
	InstanceState_INSTANCE_STATE_HEALTHY   InstanceState = 1
	InstanceState_INSTANCE_STATE_DEGRADED  InstanceState = 2
	InstanceState_INSTANCE_STATE_UNHEALTHY InstanceState = 3
)

// Enum value maps for InstanceState.
var (
	InstanceState_name = map[int32]string{
		0: "INSTANCE_STATE_UNKNOWN",
		1: "INSTANCE_STATE_HEALTHY",
		2: "INSTANCE_STATE_DEGRADED",
		3: "INSTANCE_STATE_UNHEALTHY",
	}
	InstanceState_value = map[string]int32{
		"INSTANCE_STATE_UNKNOWN":   0,
		"INSTANCE_STATE_HEALTHY":   1,
		"INSTANCE_STATE_DEGRADED":  2,
		"INSTANCE_STATE_UNHEALTHY": 3,
	}
)

func (x InstanceState) Enum() *InstanceState {
	p := new(InstanceState)
	*p = x
	return p
}

func (x InstanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hub_v1_fleet_proto_enumTypes[0].Descriptor()
}

func (InstanceState) Type() protoreflect.EnumType {
	return &file_proto_hub_v1_fleet_proto_enumTypes[0]
}

func (x InstanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceState.Descriptor instead.
func (InstanceState) EnumDescriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN       EventType = 0
	EventType_EVENT_TYPE_CONFIG_UPDATE EventType = 1
	EventType_EVENT_TYPE_DEPLOYMENT    EventType = 2
	EventType_EVENT_TYPE_DRAIN         EventType = 3
	EventType_EVENT_TYPE_PING          EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNKNOWN",
		1: "EVENT_TYPE_CONFIG_UPDATE",
		2: "EVENT_TYPE_DEPLOYMENT",
		3: "EVENT_TYPE_DRAIN",
		4: "EVENT_TYPE_PING",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNKNOWN":       0,
		"EVENT_TYPE_CONFIG_UPDATE": 1,
		"EVENT_TYPE_DEPLOYMENT":    2,
		"EVENT_TYPE_DRAIN":         3,
		"EVENT_TYPE_PING":          4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hub_v1_fleet_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_hub_v1_fleet_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{1}
}

type DeploymentStrategy int32

const (
	DeploymentStrategy_DEPLOYMENT_STRATEGY_UNKNOWN     DeploymentStrategy = 0
	DeploymentStrategy_DEPLOYMENT_STRATEGY_ALL_AT_ONCE DeploymentStrategy = 1
	DeploymentStrategy_DEPLOYMENT_STRATEGY_ROLLING     DeploymentStrategy = 2
	DeploymentStrategy_DEPLOYMENT_STRATEGY_CANARY      DeploymentStrategy = 3
)

// Enum value maps for DeploymentStrategy.
var (
	DeploymentStrategy_name = map[int32]string{
		0: "DEPLOYMENT_STRATEGY_UNKNOWN",
		1: "DEPLOYMENT_STRATEGY_ALL_AT_ONCE",
		2: "DEPLOYMENT_STRATEGY_ROLLING",
		3: "DEPLOYMENT_STRATEGY_CANARY",
	}
	DeploymentStrategy_value = map[string]int32{
		"DEPLOYMENT_STRATEGY_UNKNOWN":     0,
		"DEPLOYMENT_STRATEGY_ALL_AT_ONCE": 1,
		"DEPLOYMENT_STRATEGY_ROLLING":     2,
		"DEPLOYMENT_STRATEGY_CANARY":      3,
	}
)

func (x DeploymentStrategy) Enum() *DeploymentStrategy {
	p := new(DeploymentStrategy)
	*p = x
	return p
}

func (x DeploymentStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hub_v1_fleet_proto_enumTypes[2].Descriptor()
}

func (DeploymentStrategy) Type() protoreflect.EnumType {
	return &file_proto_hub_v1_fleet_proto_enumTypes[2]
}

func (x DeploymentStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStrategy.Descriptor instead.
func (DeploymentStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{2}
}

type DeploymentState int32

const (
	DeploymentState_DEPLOYMENT_STATE_UNKNOWN     DeploymentState = 0
	DeploymentState_DEPLOYMENT_STATE_PENDING     DeploymentState = 1
	DeploymentState_DEPLOYMENT_STATE_IN_PROGRESS DeploymentState = 2
	DeploymentState_DEPLOYMENT_STATE_VALIDATING  DeploymentState = 3
	DeploymentState_DEPLOYMENT_STATE_COMPLETED   DeploymentState = 4
	DeploymentState_DEPLOYMENT_STATE_FAILED      DeploymentState = 5
	DeploymentState_DEPLOYMENT_STATE_ROLLED_BACK DeploymentState = 6
)

// Enum value maps for DeploymentState.
var (
	DeploymentState_name = map[int32]string{
		0: "DEPLOYMENT_STATE_UNKNOWN",
		1: "DEPLOYMENT_STATE_PENDING",
		2: "DEPLOYMENT_STATE_IN_PROGRESS",
		3: "DEPLOYMENT_STATE_VALIDATING",
		4: "DEPLOYMENT_STATE_COMPLETED",
		5: "DEPLOYMENT_STATE_FAILED",
		6: "DEPLOYMENT_STATE_ROLLED_BACK",
	}
	DeploymentState_value = map[string]int32{
		"DEPLOYMENT_STATE_UNKNOWN":     0,
		"DEPLOYMENT_STATE_PENDING":     1,
		"DEPLOYMENT_STATE_IN_PROGRESS": 2,
		"DEPLOYMENT_STATE_VALIDATING":  3,
		"DEPLOYMENT_STATE_COMPLETED":   4,
		"DEPLOYMENT_STATE_FAILED":      5,
		"DEPLOYMENT_STATE_ROLLED_BACK": 6,
	}
)

func (x DeploymentState) Enum() *DeploymentState {
	p := new(DeploymentState)
	*p = x
	return p
}

func (x DeploymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hub_v1_fleet_proto_enumTypes[3].Descriptor()
}

func (DeploymentState) Type() protoreflect.EnumType {
	return &file_proto_hub_v1_fleet_proto_enumTypes[3]
}

func (x DeploymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentState.Descriptor instead.
func (DeploymentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{3}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNKNOWN       ActionType = 0
	ActionType_ACTION_TYPE_FETCH_CONFIG  ActionType = 1
	ActionType_ACTION_TYPE_APPLY_CONFIG  ActionType = 2
	ActionType_ACTION_TYPE_REPORT_STATUS ActionType = 3
	ActionType_ACTION_TYPE_DRAIN         ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNKNOWN",
		1: "ACTION_TYPE_FETCH_CONFIG",
		2: "ACTION_TYPE_APPLY_CONFIG",
		3: "ACTION_TYPE_REPORT_STATUS",
		4: "ACTION_TYPE_DRAIN",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNKNOWN":       0,
		"ACTION_TYPE_FETCH_CONFIG":  1,
		"ACTION_TYPE_APPLY_CONFIG":  2,
		"ACTION_TYPE_REPORT_STATUS": 3,
		"ACTION_TYPE_DRAIN":         4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hub_v1_fleet_proto_enumTypes[4].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_hub_v1_fleet_proto_enumTypes[4]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{4}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique instance identifier (UUID).
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Human-readable name for the instance.
	InstanceName string `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	// Machine hostname.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Agent binary version.
	AgentVersion string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Sentinel proxy version.
	SentinelVersion string `protobuf:"bytes,5,opt,name=sentinel_version,json=sentinelVersion,proto3" json:"sentinel_version,omitempty"`
	// Custom labels for filtering and grouping.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Supported agent capabilities.
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetSentinelVersion() string {
	if x != nil {
		return x.SentinelVersion
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token for subsequent calls.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Current config version to apply.
	ConfigVersion string `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Hash for change detection.
	ConfigHash string `protobuf:"bytes,3,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Recommended heartbeat interval in seconds.
	HeartbeatIntervalSeconds int32 `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *RegisterResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstanceId           string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token                string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Status               *InstanceStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentConfigVersion string                 `protobuf:"bytes,4,opt,name=current_config_version,json=currentConfigVersion,proto3" json:"current_config_version,omitempty"`
	CurrentConfigHash    string                 `protobuf:"bytes,5,opt,name=current_config_hash,json=currentConfigHash,proto3" json:"current_config_hash,omitempty"`
	Metrics              *InstanceMetrics       `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *InstanceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetCurrentConfigVersion() string {
	if x != nil {
		return x.CurrentConfigVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentConfigHash() string {
	if x != nil {
		return x.CurrentConfigHash
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() *InstanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hint to fetch new config.
	ConfigUpdateAvailable bool `protobuf:"varint,1,opt,name=config_update_available,json=configUpdateAvailable,proto3" json:"config_update_available,omitempty"`
	// Latest available config version.
	LatestConfigVersion string `protobuf:"bytes,2,opt,name=latest_config_version,json=latestConfigVersion,proto3" json:"latest_config_version,omitempty"`
	// Actions agent should take.
	Actions       []*PendingAction `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetConfigUpdateAvailable() bool {
	if x != nil {
		return x.ConfigUpdateAvailable
	}
	return false
}

func (x *HeartbeatResponse) GetLatestConfigVersion() string {
	if x != nil {
		return x.LatestConfigVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetActions() []*PendingAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type DeregisterRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token      string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Reason for deregistration.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type InstanceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State InstanceState          `protobuf:"varint,1,opt,name=state,proto3,enum=sentinel.hub.v1.InstanceState" json:"state,omitempty"`
	// Human-readable status message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Uptime in seconds.
	UptimeSeconds int64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Number of active connections.
	ActiveConnections int32 `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *InstanceStatus) GetState() InstanceState {
	if x != nil {
		return x.State
	}
	return InstanceState_INSTANCE_STATE_UNKNOWN
}

func (x *InstanceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstanceStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *InstanceStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type InstanceMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestsTotal  int64                  `protobuf:"varint,1,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	RequestsFailed int64                  `protobuf:"varint,2,opt,name=requests_failed,json=requestsFailed,proto3" json:"requests_failed,omitempty"`
	LatencyP50Ms   float64                `protobuf:"fixed64,3,opt,name=latency_p50_ms,json=latencyP50Ms,proto3" json:"latency_p50_ms,omitempty"`
	LatencyP99Ms   float64                `protobuf:"fixed64,4,opt,name=latency_p99_ms,json=latencyP99Ms,proto3" json:"latency_p99_ms,omitempty"`
	BytesSent      int64                  `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived  int64                  `protobuf:"varint,6,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceMetrics) Reset() {
	*x = InstanceMetrics{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMetrics) ProtoMessage() {}

func (x *InstanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMetrics.ProtoReflect.Descriptor instead.
func (*InstanceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *InstanceMetrics) GetRequestsTotal() int64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *InstanceMetrics) GetRequestsFailed() int64 {
	if x != nil {
		return x.RequestsFailed
	}
	return 0
}

func (x *InstanceMetrics) GetLatencyP50Ms() float64 {
	if x != nil {
		return x.LatencyP50Ms
	}
	return 0
}

func (x *InstanceMetrics) GetLatencyP99Ms() float64 {
	if x != nil {
		return x.LatencyP99Ms
	}
	return 0
}

func (x *InstanceMetrics) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *InstanceMetrics) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type GetConfigRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token      string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Optional: specific version, empty for latest.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetConfigResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hash    string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// KDL configuration content.
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *GetConfigResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetConfigResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetConfigResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetConfigResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetConfigVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConfigId      string                 `protobuf:"bytes,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,4,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigVersionRequest) Reset() {
	*x = GetConfigVersionRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigVersionRequest) ProtoMessage() {}

func (x *GetConfigVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigVersionRequest.ProtoReflect.Descriptor instead.
func (*GetConfigVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfigVersionRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetConfigVersionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConfigVersionRequest) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *GetConfigVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

type GetConfigVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ChangeSummary string                 `protobuf:"bytes,5,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigVersionResponse) Reset() {
	*x = GetConfigVersionResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigVersionResponse) ProtoMessage() {}

func (x *GetConfigVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigVersionResponse.ProtoReflect.Descriptor instead.
func (*GetConfigVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigVersionResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *GetConfigVersionResponse) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *GetConfigVersionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetConfigVersionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetConfigVersionResponse) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

func (x *GetConfigVersionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SubscribeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type      EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=sentinel.hub.v1.EventType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_ConfigUpdate
	//	*Event_Deployment
	//	*Event_Drain
	//	*Event_Ping
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetConfigUpdate() *ConfigUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *Event) GetDeployment() *DeploymentEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Deployment); ok {
			return x.Deployment
		}
	}
	return nil
}

func (x *Event) GetDrain() *DrainEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *Event) GetPing() *PingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdateEvent `protobuf:"bytes,4,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type Event_Deployment struct {
	Deployment *DeploymentEvent `protobuf:"bytes,5,opt,name=deployment,proto3,oneof"`
}

type Event_Drain struct {
	Drain *DrainEvent `protobuf:"bytes,6,opt,name=drain,proto3,oneof"`
}

type Event_Ping struct {
	Ping *PingEvent `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

func (*Event_ConfigUpdate) isEvent_Payload() {}

func (*Event_Deployment) isEvent_Payload() {}

func (*Event_Drain) isEvent_Payload() {}

func (*Event_Ping) isEvent_Payload() {}

type ConfigUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	ChangeSummary string                 `protobuf:"bytes,3,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateEvent) Reset() {
	*x = ConfigUpdateEvent{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateEvent) ProtoMessage() {}

func (x *ConfigUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateEvent.ProtoReflect.Descriptor instead.
func (*ConfigUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigUpdateEvent) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigUpdateEvent) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigUpdateEvent) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

type DeploymentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Strategy      DeploymentStrategy     `protobuf:"varint,3,opt,name=strategy,proto3,enum=sentinel.hub.v1.DeploymentStrategy" json:"strategy,omitempty"`
	// Position in rolling deployment (1-indexed).
	BatchPosition int32 `protobuf:"varint,4,opt,name=batch_position,json=batchPosition,proto3" json:"batch_position,omitempty"`
	// Total batches in deployment.
	BatchTotal int32 `protobuf:"varint,5,opt,name=batch_total,json=batchTotal,proto3" json:"batch_total,omitempty"`
	// Unix timestamp deadline.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Whether this is a rollback deployment.
	IsRollback    bool `protobuf:"varint,7,opt,name=is_rollback,json=isRollback,proto3" json:"is_rollback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentEvent) Reset() {
	*x = DeploymentEvent{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentEvent) ProtoMessage() {}

func (x *DeploymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentEvent.ProtoReflect.Descriptor instead.
func (*DeploymentEvent) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *DeploymentEvent) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentEvent) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *DeploymentEvent) GetStrategy() DeploymentStrategy {
	if x != nil {
		return x.Strategy
	}
	return DeploymentStrategy_DEPLOYMENT_STRATEGY_UNKNOWN
}

func (x *DeploymentEvent) GetBatchPosition() int32 {
	if x != nil {
		return x.BatchPosition
	}
	return 0
}

func (x *DeploymentEvent) GetBatchTotal() int32 {
	if x != nil {
		return x.BatchTotal
	}
	return 0
}

func (x *DeploymentEvent) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *DeploymentEvent) GetIsRollback() bool {
	if x != nil {
		return x.IsRollback
	}
	return false
}

type DrainEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time allowed for draining in seconds.
	DrainTimeoutSeconds int32  `protobuf:"varint,1,opt,name=drain_timeout_seconds,json=drainTimeoutSeconds,proto3" json:"drain_timeout_seconds,omitempty"`
	Reason              string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DrainEvent) Reset() {
	*x = DrainEvent{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainEvent) ProtoMessage() {}

func (x *DrainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainEvent.ProtoReflect.Descriptor instead.
func (*DrainEvent) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *DrainEvent) GetDrainTimeoutSeconds() int32 {
	if x != nil {
		return x.DrainTimeoutSeconds
	}
	return 0
}

func (x *DrainEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server timestamp for latency measurement.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingEvent) Reset() {
	*x = PingEvent{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEvent) ProtoMessage() {}

func (x *PingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEvent.ProtoReflect.Descriptor instead.
func (*PingEvent) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *PingEvent) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type AckDeploymentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceId   string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token        string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeploymentId string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Accepted     bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Reason if not accepted.
	RejectionReason string `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AckDeploymentRequest) Reset() {
	*x = AckDeploymentRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDeploymentRequest) ProtoMessage() {}

func (x *AckDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDeploymentRequest.ProtoReflect.Descriptor instead.
func (*AckDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{18}
}

func (x *AckDeploymentRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AckDeploymentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AckDeploymentRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *AckDeploymentRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AckDeploymentRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type AckDeploymentResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Optional instruction from hub.
	Instruction   string `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDeploymentResponse) Reset() {
	*x = AckDeploymentResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDeploymentResponse) ProtoMessage() {}

func (x *AckDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDeploymentResponse.ProtoReflect.Descriptor instead.
func (*AckDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{19}
}

func (x *AckDeploymentResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *AckDeploymentResponse) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type DeploymentStatusRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceId   string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Token        string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeploymentId string                 `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	State        DeploymentState        `protobuf:"varint,4,opt,name=state,proto3,enum=sentinel.hub.v1.DeploymentState" json:"state,omitempty"`
	Message      string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Error details if failed.
	ErrorDetails  string `protobuf:"bytes,6,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentStatusRequest) Reset() {
	*x = DeploymentStatusRequest{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatusRequest) ProtoMessage() {}

func (x *DeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*DeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{20}
}

func (x *DeploymentStatusRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeploymentStatusRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeploymentStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentStatusRequest) GetState() DeploymentState {
	if x != nil {
		return x.State
	}
	return DeploymentState_DEPLOYMENT_STATE_UNKNOWN
}

func (x *DeploymentStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentStatusRequest) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

type DeploymentStatusResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Optional next action instruction.
	NextAction    string `protobuf:"bytes,2,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentStatusResponse) Reset() {
	*x = DeploymentStatusResponse{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentStatusResponse) ProtoMessage() {}

func (x *DeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*DeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{21}
}

func (x *DeploymentStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *DeploymentStatusResponse) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

type PendingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActionType             `protobuf:"varint,1,opt,name=type,proto3,enum=sentinel.hub.v1.ActionType" json:"type,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingAction) Reset() {
	*x = PendingAction{}
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAction) ProtoMessage() {}

func (x *PendingAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_v1_fleet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAction.ProtoReflect.Descriptor instead.
func (*PendingAction) Descriptor() ([]byte, []int) {
	return file_proto_hub_v1_fleet_proto_rawDescGZIP(), []int{22}
}

func (x *PendingAction) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNKNOWN
}

func (x *PendingAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *PendingAction) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_proto_hub_v1_fleet_proto protoreflect.FileDescriptor

const file_proto_hub_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x18proto/hub/v1/fleet.proto\x12\x0fsentinel.hub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12)\n" +
	"\x10sentinel_version\x18\x05 \x01(\tR\x0fsentinelVersion\x12D\n" +
	"\x06labels\x18\x06 \x03(\v2,.sentinel.hub.v1.RegisterRequest.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vconfig_hash\x18\x03 \x01(\tR\n" +
	"configHash\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x05R\x18heartbeatIntervalSeconds\"\xa4\x02\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x127\n" +
	"\x06status\x18\x03 \x01(\v2\x1f.sentinel.hub.v1.InstanceStatusR\x06status\x124\n" +
	"\x16current_config_version\x18\x04 \x01(\tR\x14currentConfigVersion\x12.\n" +
	"\x13current_config_hash\x18\x05 \x01(\tR\x11currentConfigHash\x12:\n" +
	"\ametrics\x18\x06 \x01(\v2 .sentinel.hub.v1.InstanceMetricsR\ametrics\"\xb9\x01\n" +
	"\x11HeartbeatResponse\x126\n" +
	"\x17config_update_available\x18\x01 \x01(\bR\x15configUpdateAvailable\x122\n" +
	"\x15latest_config_version\x18\x02 \x01(\tR\x13latestConfigVersion\x128\n" +
	"\aactions\x18\x03 \x03(\v2\x1e.sentinel.hub.v1.PendingActionR\aactions\"b\n" +
	"\x11DeregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x12DeregisterResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xb6\x01\n" +
	"\x0eInstanceStatus\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.sentinel.hub.v1.InstanceStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\"\xf3\x01\n" +
	"\x0fInstanceMetrics\x12%\n" +
	"\x0erequests_total\x18\x01 \x01(\x03R\rrequestsTotal\x12'\n" +
	"\x0frequests_failed\x18\x02 \x01(\x03R\x0erequestsFailed\x12$\n" +
	"\x0elatency_p50_ms\x18\x03 \x01(\x01R\flatencyP50Ms\x12$\n" +
	"\x0elatency_p99_ms\x18\x04 \x01(\x01R\flatencyP99Ms\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x06 \x01(\x03R\rbytesReceived\"c\n" +
	"\x10GetConfigRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x96\x01\n" +
	"\x11GetConfigResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x94\x01\n" +
	"\x17GetConfigVersionRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\tR\bconfigId\x12%\n" +
	"\x0eversion_number\x18\x04 \x01(\x05R\rversionNumber\"\xee\x01\n" +
	"\x18GetConfigVersionResponse\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12%\n" +
	"\x0echange_summary\x18\x05 \x01(\tR\rchangeSummary\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x8d\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.sentinel.hub.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12I\n" +
	"\rconfig_update\x18\x04 \x01(\v2\".sentinel.hub.v1.ConfigUpdateEventH\x00R\fconfigUpdate\x12B\n" +
	"\n" +
	"deployment\x18\x05 \x01(\v2 .sentinel.hub.v1.DeploymentEventH\x00R\n" +
	"deployment\x123\n" +
	"\x05drain\x18\x06 \x01(\v2\x1b.sentinel.hub.v1.DrainEventH\x00R\x05drain\x120\n" +
	"\x04ping\x18\a \x01(\v2\x1a.sentinel.hub.v1.PingEventH\x00R\x04pingB\t\n" +
	"\apayload\"\x82\x01\n" +
	"\x11ConfigUpdateEvent\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12%\n" +
	"\x0echange_summary\x18\x03 \x01(\tR\rchangeSummary\"\xbf\x02\n" +
	"\x0fDeploymentEvent\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x12?\n" +
	"\bstrategy\x18\x03 \x01(\x0e2#.sentinel.hub.v1.DeploymentStrategyR\bstrategy\x12%\n" +
	"\x0ebatch_position\x18\x04 \x01(\x05R\rbatchPosition\x12\x1f\n" +
	"\vbatch_total\x18\x05 \x01(\x05R\n" +
	"batchTotal\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1f\n" +
	"\vis_rollback\x18\a \x01(\bR\n" +
	"isRollback\"X\n" +
	"\n" +
	"DrainEvent\x122\n" +
	"\x15drain_timeout_seconds\x18\x01 \x01(\x05R\x13drainTimeoutSeconds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\tPingEvent\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb9\x01\n" +
	"\x14AckDeploymentRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\"]\n" +
	"\x15AckDeploymentResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\"\xec\x01\n" +
	"\x17DeploymentStatusRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rdeployment_id\x18\x03 \x01(\tR\fdeploymentId\x126\n" +
	"\x05state\x18\x04 \x01(\x0e2 .sentinel.hub.v1.DeploymentStateR\x05state\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12#\n" +
	"\rerror_details\x18\x06 \x01(\tR\ferrorDetails\"_\n" +
	"\x18DeploymentStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1f\n" +
	"\vnext_action\x18\x02 \x01(\tR\n" +
	"nextAction\"\xdc\x01\n" +
	"\rPendingAction\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.sentinel.hub.v1.ActionTypeR\x04type\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12B\n" +
	"\x06params\x18\x03 \x03(\v2*.sentinel.hub.v1.PendingAction.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x82\x01\n" +
	"\rInstanceState\x12\x1a\n" +
	"\x16INSTANCE_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16INSTANCE_STATE_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17INSTANCE_STATE_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18INSTANCE_STATE_UNHEALTHY\x10\x03*\x87\x01\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_CONFIG_UPDATE\x10\x01\x12\x19\n" +
	"\x15EVENT_TYPE_DEPLOYMENT\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_DRAIN\x10\x03\x12\x13\n" +
	"\x0fEVENT_TYPE_PING\x10\x04*\x9b\x01\n" +
	"\x12DeploymentStrategy\x12\x1f\n" +
	"\x1bDEPLOYMENT_STRATEGY_UNKNOWN\x10\x00\x12#\n" +
	"\x1fDEPLOYMENT_STRATEGY_ALL_AT_ONCE\x10\x01\x12\x1f\n" +
	"\x1bDEPLOYMENT_STRATEGY_ROLLING\x10\x02\x12\x1e\n" +
	"\x1aDEPLOYMENT_STRATEGY_CANARY\x10\x03*\xef\x01\n" +
	"\x0fDeploymentState\x12\x1c\n" +
	"\x18DEPLOYMENT_STATE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18DEPLOYMENT_STATE_PENDING\x10\x01\x12 \n" +
	"\x1cDEPLOYMENT_STATE_IN_PROGRESS\x10\x02\x12\x1f\n" +
	"\x1bDEPLOYMENT_STATE_VALIDATING\x10\x03\x12\x1e\n" +
	"\x1aDEPLOYMENT_STATE_COMPLETED\x10\x04\x12\x1b\n" +
	"\x17DEPLOYMENT_STATE_FAILED\x10\x05\x12 \n" +
	"\x1cDEPLOYMENT_STATE_ROLLED_BACK\x10\x06*\x97\x01\n" +
	"\n" +
	"ActionType\x12\x17\n" +
	"\x13ACTION_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18ACTION_TYPE_FETCH_CONFIG\x10\x01\x12\x1c\n" +
	"\x18ACTION_TYPE_APPLY_CONFIG\x10\x02\x12\x1d\n" +
	"\x19ACTION_TYPE_REPORT_STATUS\x10\x03\x12\x15\n" +
	"\x11ACTION_TYPE_DRAIN\x10\x042\xe0\x05\n" +
	"\fFleetService\x12O\n" +
	"\bRegister\x12 .sentinel.hub.v1.RegisterRequest\x1a!.sentinel.hub.v1.RegisterResponse\x12R\n" +
	"\tHeartbeat\x12!.sentinel.hub.v1.HeartbeatRequest\x1a\".sentinel.hub.v1.HeartbeatResponse\x12U\n" +
	"\n" +
	"Deregister\x12\".sentinel.hub.v1.DeregisterRequest\x1a#.sentinel.hub.v1.DeregisterResponse\x12R\n" +
	"\tGetConfig\x12!.sentinel.hub.v1.GetConfigRequest\x1a\".sentinel.hub.v1.GetConfigResponse\x12g\n" +
	"\x10GetConfigVersion\x12(.sentinel.hub.v1.GetConfigVersionRequest\x1a).sentinel.hub.v1.GetConfigVersionResponse\x12H\n" +
	"\tSubscribe\x12!.sentinel.hub.v1.SubscribeRequest\x1a\x16.sentinel.hub.v1.Event0\x01\x12^\n" +
	"\rAckDeployment\x12%.sentinel.hub.v1.AckDeploymentRequest\x1a&.sentinel.hub.v1.AckDeploymentResponse\x12m\n" +
	"\x16ReportDeploymentStatus\x12(.sentinel.hub.v1.DeploymentStatusRequest\x1a).sentinel.hub.v1.DeploymentStatusResponseB.Z,github.com/raskell-io/sentinel-hub/pkg/hubpbb\x06proto3"

var (
	file_proto_hub_v1_fleet_proto_rawDescOnce sync.Once
	file_proto_hub_v1_fleet_proto_rawDescData []byte
)

func file_proto_hub_v1_fleet_proto_rawDescGZIP() []byte {
	file_proto_hub_v1_fleet_proto_rawDescOnce.Do(func() {
		file_proto_hub_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hub_v1_fleet_proto_rawDesc), len(file_proto_hub_v1_fleet_proto_rawDesc)))
	})
	return file_proto_hub_v1_fleet_proto_rawDescData
}

var file_proto_hub_v1_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_hub_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_hub_v1_fleet_proto_goTypes = []any{
	(InstanceState)(0),               // 0: sentinel.hub.v1.InstanceState
	(EventType)(0),                   // 1: sentinel.hub.v1.EventType
	(DeploymentStrategy)(0),          // 2: sentinel.hub.v1.DeploymentStrategy
	(DeploymentState)(0),             // 3: sentinel.hub.v1.DeploymentState
	(ActionType)(0),                  // 4: sentinel.hub.v1.ActionType
	(*RegisterRequest)(nil),          // 5: sentinel.hub.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 6: sentinel.hub.v1.RegisterResponse
	(*HeartbeatRequest)(nil),         // 7: sentinel.hub.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 8: sentinel.hub.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),        // 9: sentinel.hub.v1.DeregisterRequest
	(*DeregisterResponse)(nil),       // 10: sentinel.hub.v1.DeregisterResponse
	(*InstanceStatus)(nil),           // 11: sentinel.hub.v1.InstanceStatus
	(*InstanceMetrics)(nil),          // 12: sentinel.hub.v1.InstanceMetrics
	(*GetConfigRequest)(nil),         // 13: sentinel.hub.v1.GetConfigRequest
	(*GetConfigResponse)(nil),        // 14: sentinel.hub.v1.GetConfigResponse
	(*GetConfigVersionRequest)(nil),  // 15: sentinel.hub.v1.GetConfigVersionRequest
	(*GetConfigVersionResponse)(nil), // 16: sentinel.hub.v1.GetConfigVersionResponse
	(*SubscribeRequest)(nil),         // 17: sentinel.hub.v1.SubscribeRequest
	(*Event)(nil),                    // 18: sentinel.hub.v1.Event
	(*ConfigUpdateEvent)(nil),        // 19: sentinel.hub.v1.ConfigUpdateEvent
	(*DeploymentEvent)(nil),          // 20: sentinel.hub.v1.DeploymentEvent
	(*DrainEvent)(nil),               // 21: sentinel.hub.v1.DrainEvent
	(*PingEvent)(nil),                // 22: sentinel.hub.v1.PingEvent
	(*AckDeploymentRequest)(nil),     // 23: sentinel.hub.v1.AckDeploymentRequest
	(*AckDeploymentResponse)(nil),    // 24: sentinel.hub.v1.AckDeploymentResponse
	(*DeploymentStatusRequest)(nil),  // 25: sentinel.hub.v1.DeploymentStatusRequest
	(*DeploymentStatusResponse)(nil), // 26: sentinel.hub.v1.DeploymentStatusResponse
	(*PendingAction)(nil),            // 27: sentinel.hub.v1.PendingAction
	nil,                              // 28: sentinel.hub.v1.RegisterRequest.LabelsEntry
	nil,                              // 29: sentinel.hub.v1.PendingAction.ParamsEntry
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
}
var file_proto_hub_v1_fleet_proto_depIdxs = []int32{
	28, // 0: sentinel.hub.v1.RegisterRequest.labels:type_name -> sentinel.hub.v1.RegisterRequest.LabelsEntry
	11, // 1: sentinel.hub.v1.HeartbeatRequest.status:type_name -> sentinel.hub.v1.InstanceStatus
	12, // 2: sentinel.hub.v1.HeartbeatRequest.metrics:type_name -> sentinel.hub.v1.InstanceMetrics
	27, // 3: sentinel.hub.v1.HeartbeatResponse.actions:type_name -> sentinel.hub.v1.PendingAction
	0,  // 4: sentinel.hub.v1.InstanceStatus.state:type_name -> sentinel.hub.v1.InstanceState
	30, // 5: sentinel.hub.v1.GetConfigResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 6: sentinel.hub.v1.GetConfigVersionResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: sentinel.hub.v1.Event.type:type_name -> sentinel.hub.v1.EventType
	30, // 8: sentinel.hub.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	19, // 9: sentinel.hub.v1.Event.config_update:type_name -> sentinel.hub.v1.ConfigUpdateEvent
	20, // 10: sentinel.hub.v1.Event.deployment:type_name -> sentinel.hub.v1.DeploymentEvent
	21, // 11: sentinel.hub.v1.Event.drain:type_name -> sentinel.hub.v1.DrainEvent
	22, // 12: sentinel.hub.v1.Event.ping:type_name -> sentinel.hub.v1.PingEvent
	2,  // 13: sentinel.hub.v1.DeploymentEvent.strategy:type_name -> sentinel.hub.v1.DeploymentStrategy
	30, // 14: sentinel.hub.v1.DeploymentEvent.deadline:type_name -> google.protobuf.Timestamp
	30, // 15: sentinel.hub.v1.PingEvent.server_time:type_name -> google.protobuf.Timestamp
	3,  // 16: sentinel.hub.v1.DeploymentStatusRequest.state:type_name -> sentinel.hub.v1.DeploymentState
	4,  // 17: sentinel.hub.v1.PendingAction.type:type_name -> sentinel.hub.v1.ActionType
	29, // 18: sentinel.hub.v1.PendingAction.params:type_name -> sentinel.hub.v1.PendingAction.ParamsEntry
	5,  // 19: sentinel.hub.v1.FleetService.Register:input_type -> sentinel.hub.v1.RegisterRequest
	7,  // 20: sentinel.hub.v1.FleetService.Heartbeat:input_type -> sentinel.hub.v1.HeartbeatRequest
	9,  // 21: sentinel.hub.v1.FleetService.Deregister:input_type -> sentinel.hub.v1.DeregisterRequest
	13, // 22: sentinel.hub.v1.FleetService.GetConfig:input_type -> sentinel.hub.v1.GetConfigRequest
	15, // 23: sentinel.hub.v1.FleetService.GetConfigVersion:input_type -> sentinel.hub.v1.GetConfigVersionRequest
	17, // 24: sentinel.hub.v1.FleetService.Subscribe:input_type -> sentinel.hub.v1.SubscribeRequest
	23, // 25: sentinel.hub.v1.FleetService.AckDeployment:input_type -> sentinel.hub.v1.AckDeploymentRequest
	25, // 26: sentinel.hub.v1.FleetService.ReportDeploymentStatus:input_type -> sentinel.hub.v1.DeploymentStatusRequest
	6,  // 27: sentinel.hub.v1.FleetService.Register:output_type -> sentinel.hub.v1.RegisterResponse
	8,  // 28: sentinel.hub.v1.FleetService.Heartbeat:output_type -> sentinel.hub.v1.HeartbeatResponse
	10, // 29: sentinel.hub.v1.FleetService.Deregister:output_type -> sentinel.hub.v1.DeregisterResponse
	14, // 30: sentinel.hub.v1.FleetService.GetConfig:output_type -> sentinel.hub.v1.GetConfigResponse
	16, // 31: sentinel.hub.v1.FleetService.GetConfigVersion:output_type -> sentinel.hub.v1.GetConfigVersionResponse
	18, // 32: sentinel.hub.v1.FleetService.Subscribe:output_type -> sentinel.hub.v1.Event
	24, // 33: sentinel.hub.v1.FleetService.AckDeployment:output_type -> sentinel.hub.v1.AckDeploymentResponse
	26, // 34: sentinel.hub.v1.FleetService.ReportDeploymentStatus:output_type -> sentinel.hub.v1.DeploymentStatusResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_hub_v1_fleet_proto_init() }
func file_proto_hub_v1_fleet_proto_init() {
	if File_proto_hub_v1_fleet_proto != nil {
		return
	}
	file_proto_hub_v1_fleet_proto_msgTypes[13].OneofWrappers = []any{
		(*Event_ConfigUpdate)(nil),
		(*Event_Deployment)(nil),
		(*Event_Drain)(nil),
		(*Event_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hub_v1_fleet_proto_rawDesc), len(file_proto_hub_v1_fleet_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hub_v1_fleet_proto_goTypes,
		DependencyIndexes: file_proto_hub_v1_fleet_proto_depIdxs,
		EnumInfos:         file_proto_hub_v1_fleet_proto_enumTypes,
		MessageInfos:      file_proto_hub_v1_fleet_proto_msgTypes,
	}.Build()
	File_proto_hub_v1_fleet_proto = out.File
	file_proto_hub_v1_fleet_proto_goTypes = nil
	file_proto_hub_v1_fleet_proto_depIdxs = nil
}
